
main: Cercle.class Test.class Main.class
	java Main

Cercle.class: Cercle.java
	javac -Xlint Cercle.java 

Test.class: Test.java
	javac -Xlint Test.java

Main.class: Main.java
	javac -Xlint Main.java 